default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit, commit-msg]
repos:
- repo: local
  hooks:
  - id: check-commit-message
    name: check-commit-message
    entry: ./.pre-commit_scripts/check_commit_message.py
    language: python
    stages: [commit-msg]
  - id: check-ambiguous-constraints
    name: check-ambiguous-constraints
    entry: ./.pre-commit_scripts/check_ambiguous_constraints.py
    language: python
    stages: [pre-commit]
